site_name: Uranus Docs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.instant: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details

extra_javascript:
  - vendor/katex/katex.min.js
  - vendor/katex/contrib/auto-render.min.js
  - js/katex-init.js
  - https://fonts.googleapis.com/css2?family=Fira+Code&display=swap

extra_css:
  - vendor/katex/katex.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css
  - css/extra.css

nav:
  - Uranus:
      - index.md
      - What is Uranus?: uranus/overview.md
      - Use Cases: uranus/use-cases.md
      - User Roles: uranus/user-roles.md
      - Core Entities:
          - uranus/core/index.md
          - Organizer: uranus/core/organizer.md
          - Venue: uranus/core/venue.md
          - Space: uranus/core/space.md
          - Event: uranus/core/event.md
          - Event Date: uranus/core/event-date.md
          - Event Contributor: uranus/core/event-contributor.md
          - Image: uranus/core/image.md
      - Language Support: uranus/language-support.md
      - Technical Foundation:
          - uranus/index.md
          - API Server:
              - uranus/api-server/index.md
  - Database:
      - database/index.md
      - User:
          - database/user/index.md
          - user: database/user/user.md
      - Event:
          - database/event/index.md
          - event: database/event/event.md
          - event_date: database/event/event-date.md
  - API:
      - api/index.md
      - Permission System: api/permission-system.md
      - Public:
          - api/public/index.md
          - /login: api/public/login.md
          - GET:
              - choosable: api/public/get/choosable.md
              - events: api/public/get/events.md
          - meta: api/public/meta.md
          - event/images: api/public/event-images.md
      - Admin:
          - api/admin/index.md
          - /permissions/list: api/admin/get-permissions-list.md
          - /user/profile: api/admin/get-user-profile.md
          - /user/messages: api/admin/get-user-messages.md
          - /user/todos: api/admin/get-user-todos.md
          - /user/todo/#: api/admin/get-user-todo.md
          - /user/choosable-organizations: api/admin/get-user-choosable-organizations.md
          - /user/event/notifications: api/admin/get-user-event-notifications.md
          - /user/choosable-event-places: api/admin/get-user-choosable-event-spaces.md
          - /organization/#: api/admin/get-organization.md
          - /organization/#/member/#/permissions: api/admin/get-organization-member-permissions.md
          - Create Event: api/admin/create-event.md
      - Implementation: api/implementation.md
  - Frontend:
      - frontend/index.md
      - Login: frontend/login.md
      - New User: frontend/new-user.md
      - Dashboard: frontend/dashboard.md
      - Import: frontend/import.md
      - Export: frontend/export.md
      - Vue3 Implementation:
          - frontend/implementation/index.md
  - Integration:
      - integration/index.md
  - Use of Standards:
      - standards/index.md
  - Ideas:
      - ideas/index.md
